# Generated by Django 5.0.7 on 2024-08-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='progamme',
            name='programmeduration',
            field=models.IntegerField(default=3),
        ),
    ]
