# Generated by Django 5.0.7 on 2024-09-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progamme',
            new_name='Programme',
        ),
    ]
