# Generated by Django 5.0.7 on 2024-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0005_rename_progamme_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('mentorname', models.TextField(max_length=70)),
                ('mentor_student', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
