# Generated by Django 5.0.7 on 2024-09-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0006_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studmentor',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='busticket.mentor'),
        ),
    ]
