# Generated by Django 5.0.7 on 2024-09-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0007_student_studmentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studmentor',
            new_name='studmentorid',
        ),
    ]
