# Generated by Django 5.0.7 on 2024-10-01 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0008_rename_studmentor_student_studmentorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studmentorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busticket.mentor'),
        ),
    ]
